persistence:
  enabled: false
replicas: 1

http:
  enabled: true

secret:
  enabled: true

networkPolicy:
  elasticsearch-master-http-client: "true"
  elasticsearch-master-transport-client: "true"

xpack.security.enabled: false

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false

