
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: compose-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"   
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:     
  rules:
  - host: composedb.index.as
    http:
      paths:
      - path: /composedb(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: composedb
            port:
              number: 80              
      - path: /search(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: search
            port:
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ceramic-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"   
spec:     
  rules:
  - host: ceramic.index.as
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ceramic
            port:
              number: 80